In [1]:
import numpy as np

In [11]:
def gradient_descent(x,y):
    m_curr = b_curr = 0
    iterations = 10000
    n = len(x)
    learning_rate = 0.01
    
    for i in range(iterations):
        y_predicted = m_curr * x + b_curr
        cost = (1/n) * sum([val**2 for val in (y-y_predicted)])
        md = -(2/n)*sum (x*(y-y_predicted))
        bd = -(2/n)*sum (y-y_predicted)
        m_curr = m_curr - learning_rate * md
        b_curr = m_curr - learning_rate * bd
        ## print("m {}, b {}, cost {} iteration {}".format(m_curr, b_curr, cost, i))
  



In [12]:
x = np.array([1,2,3,4,5])
y = np.array([5,7,9,11,13])

In [13]:
gradient_descent(x,y)

In [1]:
## One hot encoding

In [3]:
import pandas as pd
df = pd.read_csv("homeprices.csv")
df

town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [5]:
dummies = pd.get_dummies(df.town)

In [7]:
merged = pd.concat([df, dummies], axis = 'columns')
merged

town  area   price  monroe township  robinsville  west windsor
0   monroe township  2600  550000                1            0             0
1   monroe township  3000  565000                1            0             0
2   monroe township  3200  610000                1            0             0
3   monroe township  3600  680000                1            0             0
4   monroe township  4000  725000                1            0             0
5      west windsor  2600  585000                0            0             1
6      west windsor  2800  615000                0            0             1
7      west windsor  3300  650000                0            0             1
8      west windsor  3600  710000                0            0             1
9       robinsville  2600  575000                0            1             0
10      robinsville  2900  600000                0            1             0
11      robinsville  3100  620000                0            1             0
12      robinsville  3600  695000                0            1             0

In [8]:
# always drop one of the dummy variable, this may create dummy variable trap
#when one variable can be derived from other variable this is called multicolinear and this may create  dummy variable trap 

In [10]:
final = merged.drop(['town', 'west windsor'], axis = 'columns')
final

area   price  monroe township  robinsville
0   2600  550000                1            0
1   3000  565000                1            0
2   3200  610000                1            0
3   3600  680000                1            0
4   4000  725000                1            0
5   2600  585000                0            0
6   2800  615000                0            0
7   3300  650000                0            0
8   3600  710000                0            0
9   2600  575000                0            1
10  2900  600000                0            1
11  3100  620000                0            1
12  3600  695000                0            1

In [11]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [21]:
X = final.drop('price', axis = 'columns')
X

area  monroe township  robinsville
0   2600                1            0
1   3000                1            0
2   3200                1            0
3   3600                1            0
4   4000                1            0
5   2600                0            0
6   2800                0            0
7   3300                0            0
8   3600                0            0
9   2600                0            1
10  2900                0            1
11  3100                0            1
12  3600                0            1

In [24]:
y = final.price
y
#dependent variable-Y 

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [25]:
model.fit(X, y)

LinearRegression()

In [26]:
model.predict([[2800,0,1]])

array([590775.63964739])

In [28]:
model.predict([[3400,0,0]])

array([681241.66845839])

In [29]:
model.score(X,y)

0.9573929037221873

In [30]:
df

town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [32]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [34]:
dfle = df
dfle.town = le.fit_transform(dfle.town)
dfle

town  area   price
0      0  2600  550000
1      0  3000  565000
2      0  3200  610000
3      0  3600  680000
4      0  4000  725000
5      2  2600  585000
6      2  2800  615000
7      2  3300  650000
8      2  3600  710000
9      1  2600  575000
10     1  2900  600000
11     1  3100  620000
12     1  3600  695000

In [36]:
X = dfle[['town', 'area']].values
X

array([[   0, 2600],
       [   0, 3000],
       [   0, 3200],
       [   0, 3600],
       [   0, 4000],
       [   2, 2600],
       [   2, 2800],
       [   2, 3300],
       [   2, 3600],
       [   1, 2600],
       [   1, 2900],
       [   1, 3100],
       [   1, 3600]], dtype=int64)

In [37]:
Y = dfle.price
Y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [66]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from sklearn.compose import ColumnTransformer
## ohe = OneHotEncoder(categorical_features=[0])
ct = ColumnTransformer([("Country", OneHotEncoder(), [0])], remainder = 'passthrough')

In [67]:
#ohe.fit_transform(X).toarray()
ct.fit_transform(X)

ValueError: all features must be in [0, -1] or [-0, 0]

In [61]:
X = X[:,1:]
X

array([], shape=(13, 0), dtype=int64)

In [68]:
model.fit(X,y)

ValueError: Found array with 0 feature(s) (shape=(13, 0)) while a minimum of 1 is required.

In [69]:
model.predict([[1,0,2800]])

array([-39867261.83616422])